config/routes.rb
require 'api/project'
require 'api/api'

TestGem::Application.routes.draw do

  #加载api
  mount Project::Api => '/'
  mount Api::Api => '/'

  root :to => 'homes#index'

  resources :homes

  resources :articles


  namespace 'rou' do
    devise_for :users ,:controllers => {:sessions => :sessions,
                                        :registrations => :registrations
    }

    root :to => 'articles#index'
    resources :homes

    resources :users do
      post :get_arr,:on => :collection
      get :login, :on => :collection
      post :login, :on => :collection
      get :log_out, :on => :collection
    end

    resources :articles

    resources :categories
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_protected
  belongs_to :category
  scope :recent,order('created_at desc')
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article
    if params[:category_id].present?
      @articles = @articles.where(:category_id => params[:category_id])
    end
    @articles = @articles.paginate(:page => params[:page],:per_page => 3)
  end

  def show
    @article = Article.find params[:id]
  end
end

app/controllers/rou/articles_controller.rb
class Rou::ArticlesController < Rou::ApplicationController
  before_filter :find_article,:only => [:edit,:update,:destroy,:show]
  before_filter :current_user_info
  def index
    @web_title = '文章列表'
    @articles =  Article
    if params[:category_id].present?
      @articles = @articles.where(:category_id => params[:category_id])
    end
    @articles = @articles.order('created_at desc').paginate(:page =>params[:page],:per_page => 4)
  end

  def new
    @web_title = '新文章'
    @article = Article.new
  end

  def show
    @web_title = '文章'
  end

  def create
    @article = Article.new params[:article]
    if @article.save
      redirect_to rou_articles_path,:notice => '创建成功'
    else
      render 'new'
    end
  end

  def edit
    @web_title = '编辑文章'
  end

  def update
    @article.update_attributes params[:article]
    if @article.save
      redirect_to rou_articles_path,:notice => '更新成功'
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to rou_articles_path,:notice => '删除成功'
  end

  private
  def find_article
    @article = Article.find params[:id]
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/rou/articles_helper.rb
module Rou::ArticlesHelper
end

app/views/articles/index.html.erb
<% if notice %>
  <script type="text/javascript">
    alert("<%= notice %>")
  </script>
<% end %>



<div class="column" style="width: 70%;overflow: hidden;font-size: 14px">
  <div class="ui raised segment">
    <% @articles.each do |article| %>
      <div class="ui teal ribbon label"><a href="<%= article_path(:id =>article.id) %>" style="">《<%=article.title%></a> </div>
      <br/>
      <%=  raw article.introduce%>
      <br/>
      <br/>
      <a href="<%= article_path(:id =>article.id) %>" class="tiny ui active button">继续阅读</a>
      <span style="float: right" class="ui green label"><%= article.created_at.strftime('%Y年%m月%d日') %></span>
      <div style="height: 28px"><%= image_tag 'fenggexian.png',:style => 'width:100%' %></div>
    <% end %>
  </div>
  <div style="text-align: center">  <%= will_paginate @articles %>
  </div>
</div>

<div class="column" style="width: 28%">
  <div class="ui secondary vertical pointing menu">
    <a class="item active">
      <i class="home icon"></i> 主页
    </a>
    <a class="item">
      <i class="mail icon"></i> 消息
    </a>
    <a class="item">
      <i class="user icon"></i> 朋友们
    </a>
  </div>
  <div class="ui secondary vertical pointing menu">
    <a class="item active">
      <i class="home icon"></i> 近期文章
    </a>
    <% recent_articles.each do |article|%>
      <a class="item" style="font-size: 14px" href="<%= article_path(:id => article.id) %>">
        <%= article.title %>
      </a>
    <% end %>
  </div>
  <div class="ui secondary vertical pointing menu">
    <a class="item active">
      <i class="home icon"></i> 文章分类
    </a>
    <a class="item" style="font-size: 14px" href="<%= articles_path %>">
      所有文章(<span style="color: peachpuff"><%= Article.count%></span>)
    </a>
    <% categories.each do |category|%>
      <a class="item" style="font-size: 14px" href="<%= articles_path(:category_id => category.id) %>">
        <%= category.name %>(<span style="color: peachpuff"><%= Article.where(:category_id => category.id).count%></span>)
      </a>
    <% end %>
  </div>
</div>





<script type="text/javascript">
  $(function(){
    $('.circular.heart.icon.link').popup().click(function(){
      $('.vertical.sidebar').first().sidebar('toggle');
    });
  })
</script>
<style type="text/css">
  * {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
  }
</style>

app/views/articles/show.html.erb
<div class="column" style="width: 95%;overflow: hidden;">
  <div class="ui items">
    <div class="item" style="width: 100%">
      <div class="content">
        <div class="meta"><span class="ui green label"><%= @article.created_at.strftime("%Y年%m月%d日") %></span>|<a href="<%= url_for root_url %>" ><i class="reply mail icon"></i></a></div>
        <div class="name"><%= @article.title%></div>
        <p class="description"><%= raw @article.content %></p>
      </div>
      <div class="extra">
        199 喜欢
      </div>
    </div>
  </div>
</div>