config/routes.rb
require 'api/project'
require 'api/api'

TestGem::Application.routes.draw do

  #加载api
  mount Project::Api => '/'
  mount Api::Api => '/'

  root :to => 'homes#index'

  resources :homes

  resources :articles


  namespace 'rou' do
    devise_for :users ,:controllers => {:sessions => :sessions,
                                        :registrations => :registrations
    }

    root :to => 'articles#index'
    resources :homes

    resources :users do
      post :get_arr,:on => :collection
      get :login, :on => :collection
      post :login, :on => :collection
      get :log_out, :on => :collection
    end

    resources :articles

    resources :categories
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  validates_presence_of :name
  validates_presence_of :password
  validates_length_of :password, :minimum => 6
  validates_confirmation_of :password
  #devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :name, :password, :password_confirmation
  has_many :focus_users ,:through => :relationships
  has_many :relationships ,:foreign_key => 'be_focus_user_id',:dependent => :destroy
  has_many :be_focus_users, :through => :reverse_relationships
  has_many :reverse_relationships ,:foreign_key => 'focus_user_id',:class_name => "Relationship" ,:dependent => :destroy

  has_many :collection_users,:through => :collection_relationships
  has_many :collection_relationships ,:foreign_key => 'be_collection_user_id',:dependent => :destroy
  has_many :be_collection_users,:through => :reverse_collection_relationships
  has_many :reverse_collection_relationships,:foreign_key => 'collection_user_id',:class_name => 'CollectionRelationship',:dependent => :destroy

  scope :order_desc,order('id desc')

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def self.find_user(name,password)
    passwd = Digest::SHA1.hexdigest(password)
    user = User.where(:name => name,:password => passwd)
    if user.present?
      @current_user = user.first
    else
      nil
    end
  end


  #def password
  #  @password
  #end
  #
  #def password=(pass)
  #  return unless pass
  #  @password = pass
  #  generate_password(pass)
  #end
  #
  #
  ## 此处用动词形式(authenticate)更加合适, 特此说明一下. 感谢 Chen Kai 同学的提醒.
  #def self.authentication(login, password)
  #  user = User.find_by_login(login)
  #  if user && Digest::SHA256.hexdigest(password + user.salt) == user.hashed_password
  #    return user
  #  end
  #  false
  #end
  #
  #private
  #def generate_password(pass)
  #  salt = Array.new(10){rand(1024).to_s(36)}.join
  #  self.salt, self.hashed_password =
  #      salt, Digest::SHA256.hexdigest(pass + salt)
  #end

end

app/controllers/rou/users_controller.rb
require 'digest/sha1'
class Rou::UsersController < Rou::ApplicationController
  before_filter :current_user_info,:except =>[:login,:log_out,:create]

  def login
    if request.post?
      user = User.find_user(params[:name],params[:password])
      if user.present?
        session[:user] = user.id
        redirect_to  session[:url].present? ? session[:url]:rou_articles_path
      else
        session[:user] = nil
        render login_rou_users_path,:layout => false
      end
    else
      render login_rou_users_path,:layout => false
    end

  end

  def log_out
    session[:user] = nil
    redirect_to  session[:url].present? ? session[:url]:rou_articles_path
  end

  def index
    @users = User.order_desc.all
    respond_to do |format|
      format.html
      format.xls {
        send_data @users.to_xls(:columns => [:name],:headers => ['姓名']), :filename => 'users22.xls'
      }
    end
  end

  def new
    @user = User.new
  end

  def create
    params[:user][:password] = Digest::SHA1.hexdigest(params[:user][:password])
    params[:user][:password_confirmation] = Digest::SHA1.hexdigest(params[:user][:password_confirmation])
    @user = User.new params[:user]
    if @user.save
      session[:user] = @user.id
      redirect_to rou_articles_path
    else
      render login_rou_users_path,:layout => false
    end

  end

  def get_arr
    user_id = params[:user_id]
    user = User.where(:id => user_id)
    render :json => user.to_json
  end

  def edit
    @user = User.find params[:id]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  autocomplete :user, :name,:full => true

  def index
    @users = User.order_desc.all

    #UserMailer.welcome_email.deliver

    @user_name = User.first.name
    @user_arr = User.where(:name => @user_name)

    respond_to do |format|
      format.html
      format.xls {
        send_data @users.to_xls(:columns => [:name],:headers => ['姓名']), :filename => 'users22.xls'
      }
    end
  end

  def new
    @user = User.new
  end

  def create

  end

  def get_arr
    user_id = params[:user_id]
    user = User.where(:id => user_id)
    render :json => user.to_json
  end

  def edit
    @user = User.find params[:id]
  end

end

app/views/users/index.html.erb
<style>
  .ui-helper-hidden-accessible { display:none; }
</style>
<table class="ui green table segment">
  <tr>
    <th>name</th>
    <th>关注用户</th>
  </tr>
  <% @users.each do |user| %>
  <tr>
    <td><a class="ui image label">
      <%= user.name %>
      <i class="delete icon"></i>
    </a></td>
    <td><%= user.name %>111</td>
  </tr>
  <% end %>
</table>
<input type="text" data-autocomplete="users/autocomplete_user_name" multiple="true">

autocomplete: <input type="text" id="auto" name="auto"/>
<%= collection_select(:user,:a,User.all,:id,:name,{},{:class => 'ui selection dropdown'})%>
<div class="ui selection dropdown">
  <input type="hidden" name="user[a]">
  <div class="text">姓名</div>
  <i class="dropdown icon"></i>
  <div class="menu">
    <% User.all.each do |u| %>
    <div class="item" data-value="<%= u.id %>"><%= u.name%></div>
    <% end %>
  </div>
</div>
<%= select('user','b',User.all.collect{|u|[u.name,u.id]}) %>

用户名：<select name="user1" id="user1">
  <option value="0">test</option>
  <% @user_arr.each do |u| %>
    <option value="<%=u.id%>"><%=u.name%></option>
  <% end %>
</select>
<select name="user2" id="user2">

</select>


<div class="red button" style="margin-left: 300px">2222</div>


<div class="column"><i class="archive icon large red"></i>Save</div>

<i class=" large circular inverted teal users icon"></i>


<div class="ui  vertical menu">
  <a class="active item">
    <i class="users icon"></i>
    朋友们
  </a>
  <a class="item">
    <i class="mail icon"></i> 消息
  </a>
  <a class="item">
    <i class="user icon"></i> 朋友们
  </a>
  <div class="ui dropdown item">
    More <i class="dropdown icon"></i>
    <div class="menu">
      <a class="item"><i class="edit icon"></i>编辑个人信息</a>
      <a class="item"><i class="globe icon"></i>选择语言</a>
      <a class="item"><i class="settings icon"></i>账户设置</a>
    </div>
  </div>
</div>
<div class="ui text menu">
  <div class="header item">排序</div>
  <a class="active item">
    <i class="home icon"></i> 最近
  </a>
  <a class="item">
    <i class="mail icon"></i> 最多最近评论
  </a>
  <a class="item" id="bbb">
    <i class="user icon"></i> 最流行
  </a>
</div>

<div class="ui items">
  <div class="item">
    <div class="content">
      <div class="meta">2天前</div>
      <div class="name">爱酷学习网天前Bootstrap视频教程</div>
      <p class="description">Bootstrap是由Twitter开发的一个前端框架，和Semantic UI类似，不过没有Semantic UI这么多的控件，和Semantic UI比起来稍微差一些。</p>
    </div>
    <div class="extra">
      199 喜欢
    </div>
  </div>
  <div class="item">
    <div class="content">
      <div class="meta">5天前</div>
      <div class="name">爱酷学习网Semantic UI视频教程</div>
      <p class="description">以Semantic UI中文网为依托对Semantic UI的各个控件、模块以及元素进行讲解。</p>
    </div>
    <div class="extra">
      311 喜欢
    </div>
  </div>
  <div class="item">
    <div class="content">
      <div class="meta">1周前</div>
      <div class="name">爱酷学习网ExtJS视频教程</div>
      <p class="description">ExtJS是一个重量级的前端框架，非常重量级，如果没有特殊需要，不要使用这个框架。ExtJS可以做到完全的Ajax化，但是类库大，学习曲线高，且就算是压缩后的文件大小也非常大，影响它的使用。</p>
    </div>
    <div class="extra">
      522 喜欢
    </div>
  </div>
</div>
<script type="text/javascript">
 $('#bbb').click(function(){
     $('.ui.sidebar').sidebar();
 });

 $(function() {

   $('#user1').change(function(){
     user_id = $(this).val();
     $("#user2 option").remove();
     $.ajax({
       url:"<%= get_arr_users_url%>",
       data:{user_id:user_id},
       type:'post',
       dataType:'json',
       success:function(data){
         if(data!=null && data != ''){
           $.each(data,function(k,v){
             $('#user2').append("<option value="+ v.id+">"+ v.name+"</option>")
           })
         }
       }
     })


   })

    var data = "Core Selectors Attributes Traversing Manipulation CSS Events Effects Ajax Utilities".split(" ");
   $("#auto").autocomplete({
     autoFocus: true,
     source: function(request, response) {
       var term = request.term, //request.term为输入的字符串
           ix = term.indexOf("@"),
           name = term, // 用户名
           host = "", // 域名
           result = []; // 结果
       result.push(term);
// result.push({ label: term, value: term }); // json格式
       if (ix > -1) {
         name = term.slice(0, ix);
         host = term.slice(ix + 1);
       }
       if (name) {
         var findedHosts = (host ? $.grep(hosts, function(value) {
               return value.indexOf(host) > -1;
             }) : data),
             findedResults = $.map(findedHosts, function(value) {
               return name + "@" + value; //返回字符串格式
// return { label: name + " @ " + value, value: name + "@" + value }; // json格式
             });
         result = result.concat($.makeArray(findedResults));
       }
       response(result);//呈现结果
     }


   });


 });
</script>