config/routes.rb
require 'api/project'
require 'api/api'

TestGem::Application.routes.draw do

  #加载api
  mount Project::Api => '/'
  mount Api::Api => '/'

  root :to => 'homes#index'

  resources :homes

  resources :articles


  namespace 'rou' do
    devise_for :users ,:controllers => {:sessions => :sessions,
                                        :registrations => :registrations
    }

    root :to => 'articles#index'
    resources :homes

    resources :users do
      post :get_arr,:on => :collection
      get :login, :on => :collection
      post :login, :on => :collection
      get :log_out, :on => :collection
    end

    resources :articles

    resources :categories
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_protected
  belongs_to :category
  scope :recent,order('created_at desc')
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article
    if params[:category_id].present?
      @articles = @articles.where(:category_id => params[:category_id])
    end
    @articles = @articles.paginate(:page => params[:page],:per_page => 3)
  end

  def show
    @article = Article.find params[:id]
  end
end

app/controllers/rou/application_controller.rb
class Rou::ApplicationController < ApplicationController
 layout 'rou/layouts/application'
 helper_method :current_user

  def login?
    unless @current_user.present?
      remember_redirect_url
      redirect_to login_rou_users_path,:layout => false
    end
  end

  def remember_redirect_url
    session[:url] = request.fullpath unless request.fullpath.include? '/rou/users/login'
  end

  def current_user_info
    if session[:user].present?
      @current_user = User.where(:id =>session[:user]).first
    end
    login?
    @current_user
  end

 def current_user
   current_user_info
 end

 if Rails.env.production?
   unless Rails.application.config.consider_all_requests_local
 rescue_from Exception, with: :render_404
 rescue_from ActionController::RoutingError, with: :render_404
 rescue_from ActionController::UnknownController, with: :render_404
 rescue_from ActionController::UnknownAction, with: :render_404
 rescue_from ActiveRecord::RecordNotFound, with: :render_404
 end
 end

 private
 def render_404(exception)
   @not_found_path = exception.message
   respond_to do |format|
     format.html { render template: 'rou/errors/not_found', layout: 'rou/layouts/application', status: 404 }
     format.all { render nothing: true, status: 404 }
   end
 end

end

app/controllers/rou/articles_controller.rb
class Rou::ArticlesController < Rou::ApplicationController
  before_filter :find_article,:only => [:edit,:update,:destroy,:show]
  before_filter :current_user_info
  def index
    @web_title = '文章列表'
    @articles =  Article
    if params[:category_id].present?
      @articles = @articles.where(:category_id => params[:category_id])
    end
    @articles = @articles.order('created_at desc').paginate(:page =>params[:page],:per_page => 4)
  end

  def new
    @web_title = '新文章'
    @article = Article.new
  end

  def show
    @web_title = '文章'
  end

  def create
    @article = Article.new params[:article]
    if @article.save
      redirect_to rou_articles_path,:notice => '创建成功'
    else
      render 'new'
    end
  end

  def edit
    @web_title = '编辑文章'
  end

  def update
    @article.update_attributes params[:article]
    if @article.save
      redirect_to rou_articles_path,:notice => '更新成功'
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to rou_articles_path,:notice => '删除成功'
  end

  private
  def find_article
    @article = Article.find params[:id]
  end
end

app/controllers/rou/categories_controller.rb
class Rou::CategoriesController < Rou::ApplicationController
  before_filter :current_user_info
  def index
    @web_title = '分类目录'
    @categories= Category.paginate(:page => params[:page], :per_page => 20)
  end

  def new
    @web_title = '新增分类'
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])
    if @category.save
      redirect_to rou_categories_path,:notice => '创建成功'
    else
      render 'new'
    end
  end

  def edit
    @web_title = '编辑'
    @category = Category.find params[:id]
  end

  def update
    @category = Category.find params[:id]
    @category.update_attributes params[:category]
    if @category.save
      redirect_to rou_categories_path,:notice => '更新成功'
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find params[:id]
    @category.destroy
    redirect_to rou_categories_path,:notice => '删除成功'
  end


end

app/controllers/rou/homes_controller.rb
class Rou::HomesController < Rou::ApplicationController
  before_filter :current_user_info
  def index
    a = request.user_agent.include?('chrome')
    logger.info a
  end

  def show
    redirect_to :action => 'index'
  end

  def new
  end
end

app/controllers/rou/sessions_controller.rb
class Rou::SessionsController < Devise::SessionsController
  layout 'rou/layouts/session'
end

app/controllers/rou/users_controller.rb
require 'digest/sha1'
class Rou::UsersController < Rou::ApplicationController
  before_filter :current_user_info,:except =>[:login,:log_out,:create]

  def login
    if request.post?
      user = User.find_user(params[:name],params[:password])
      if user.present?
        session[:user] = user.id
        redirect_to  session[:url].present? ? session[:url]:rou_articles_path
      else
        session[:user] = nil
        render login_rou_users_path,:layout => false
      end
    else
      render login_rou_users_path,:layout => false
    end

  end

  def log_out
    session[:user] = nil
    redirect_to  session[:url].present? ? session[:url]:rou_articles_path
  end

  def index
    @users = User.order_desc.all
    respond_to do |format|
      format.html
      format.xls {
        send_data @users.to_xls(:columns => [:name],:headers => ['姓名']), :filename => 'users22.xls'
      }
    end
  end

  def new
    @user = User.new
  end

  def create
    params[:user][:password] = Digest::SHA1.hexdigest(params[:user][:password])
    params[:user][:password_confirmation] = Digest::SHA1.hexdigest(params[:user][:password_confirmation])
    @user = User.new params[:user]
    if @user.save
      session[:user] = @user.id
      redirect_to rou_articles_path
    else
      render login_rou_users_path,:layout => false
    end

  end

  def get_arr
    user_id = params[:user_id]
    user = User.where(:id => user_id)
    render :json => user.to_json
  end

  def edit
    @user = User.find params[:id]
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/rou/articles_helper.rb
module Rou::ArticlesHelper
end

app/helpers/rou/categories_helper.rb
module Rou::CategoriesHelper
end

app/views/rou/articles/_form.html.erb
<div class="hr hr-24"></div>
<%= form_for [:controllers, @article], :html => {:class => 'form-horizontal'}, :role => 'form' do |f| %>
  <div class="form-group">
    <label class="col-sm-1 control-label no-padding-right" for="form-field-1"> 标题 </label>

    <div class="col-sm-9">
      <%= f.text_field :title, :class => 'col-xs-10 col-sm-5' %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-1 control-label no-padding-right" for="form-field-1">文章类别</label>

    <div class="col-sm-9">
      <div>
        <%= f.select :category_id,Category.all.collect{|c|[c.name,c.id]},{},:class => 'width-80 chosen-select','data-placeholder'=>"Choose a Country..."%>

      </div>
    </div>
  </div>


  <!--<div class="space-4"></div>-->

  <!--<div class="form-group">-->
  <!--<label class="col-sm-1 control-label no-padding-right" for="form-field-2"> Password Field </label>-->

  <!--<div class="col-sm-9">-->
  <!--<input type="password" id="form-field-2" placeholder="Password" class="col-xs-10 col-sm-5">-->
  <!--</div>-->
  <!--</div>-->

  <div class="space-4"></div>
  <div class="form-group">
    <label class="col-sm-1 control-label no-padding-right" for="form-field-2">简介</label>

    <div class="col-sm-9">
      <%= f.text_area :introduce, :class => 'form-control', :rows => '10' %>
    </div>
  </div>

  <div class="space-4"></div>
  <div class="form-group">
    <label class="col-sm-1 control-label no-padding-right" for="form-field-2"> 内容 </label>

    <div class="col-sm-9">
      <%= f.kindeditor :content, :window_onload => true,:editor_id => 'my_editor' %>
    </div>
  </div>

  <div class="clearfix form-actions">
    <div class="col-md-offset-3 col-md-9">
      <button class="btn btn-info sub" type="button">
        <i class="icon-ok bigger-110"></i>
        提交
      </button>

      &nbsp; &nbsp; &nbsp;
      <button class="btn" type="reset">
        <i class="icon-undo bigger-110"></i>
        重置
      </button>
    </div>
  </div>

  <div class="hr hr-24"></div>

<% end %>
<script>
  $(function(){
    $(".chosen-select").chosen();
  });
    $('.sub').eq(0).click(function(){
      var text = my_editor.html();
      $('#article_content').html(text);
      $('.form-horizontal').submit();
    })
</script>
<%= javascript_include_tag 'kindeditor/kindeditor' %>

app/views/rou/articles/edit.html.erb
<div class="main-content">
  <div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
      try {
        ace.settings.check('breadcrumbs', 'fixed')
      } catch (e) {
      }
    </script>

    <ul class="breadcrumb">
      <li>
        <i class="icon-home home-icon"></i>
        <a href="<%= rou_root_url %>">Home</a>
      </li>
      <li class="active">Article</li>
    </ul>
    <!-- .breadcrumb -->

    <!-- #nav-search -->
  </div>

  <div class="page-content">

    <div class="row">
      <div class="col-xs-12">
        <!-- PAGE CONTENT BEGINS -->

        <div class="row">
          <div class="col-sm-12 widget-container-span">
            <div class="widget-box">
              <div class="widget-header widget-hea1der-small header-color-dark">
                <h6><%= @web_title %></h6>
                <div class="widget-toolbar">
                  <%= link_to '新增', new_rou_article_path %>
                </div>
              </div>
              <%= render 'form' %>
            </div>

          </div>
        </div>
      </div>
    </div>

    <div class="space-24"></div>

  </div>
  <!-- /.col -->
</div><!-- /.row -->

app/views/rou/articles/index.html.erb
<div class="main-content">
  <div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
      try {
        ace.settings.check('breadcrumbs', 'fixed')
      } catch (e) {
      }
    </script>

    <ul class="breadcrumb">
      <li>
        <i class="icon-home home-icon"></i>
        <a href="<%= rou_root_url %>">Home</a>
      </li>
      <li class="active">Article</li>
    </ul>
    <!-- .breadcrumb -->

    <!-- #nav-search -->
  </div>

  <div class="page-content">

    <div class="row">
      <div class="col-xs-12">
        <!-- PAGE CONTENT BEGINS -->

        <div class="row">
          <div class="col-sm-12 widget-container-span">
            <div class="widget-box">
              <div class="widget-header widget-hea1der-small header-color-dark">
                <h6><%= @web_title %></h6>
                <div class="widget-toolbar">
                  <%= link_to '新增', new_rou_article_path,:style => 'color:wite' %>
                </div>
              </div>
              <div class="table-responsive">
                <table id="sample-table-1" class="table table-striped table-bordered table-hover">
                  <thead>
                  <tr>
                    <th class="center">
                      <label>
                        <input type="checkbox" class="ace">
                        <span class="lbl"></span>
                      </label>
                    </th>
                    <th>ID</th>
                    <th>标题</th>
                    <th class="hidden-480">简介</th>
                    <th class="hidden-480">类别</th>
                    <th>
                      <i class="icon-time bigger-110 hidden-480"></i>
                      创建时间
                    </th>
                    <th>操作</th>
                  </tr>
                  </thead>

                  <tbody>
                  <% @articles.each do |article| %>
                  <tr class="">
                    <td class="center">
                      <label>
                        <input type="checkbox" class="ace">
                        <span class="lbl"></span>
                      </label>
                    </td>

                    <td>
                      <%= article.id %>
                    </td>
                    <td><%= article.title %></td>
                    <td class="hidden-480"><%= article.introduce[0..10]%>...</td>
                    <td><%= article.try(:category).try(:name) %></td>
                    <td class="hidden-480">
                      <span class="label label-sm label-warning"><%= article.created_at.strftime('%Y-%m-%d') %></span>
                    </td>

                    <td>
                      <div class="visible-md visible-lg hidden-sm hidden-xs btn-group">
                        <%= link_to rou_article_path(article),:class => 'btn btn-xs btn-success' do  %>
                          <i class=" icon-comment-alt bigger-120"></i>
                        <% end %>

                        <%= link_to edit_rou_article_path(article),:class => 'btn btn-xs btn-info' do  %>
                          <i class="icon-edit bigger-120"></i>
                        <% end %>

                        <%= link_to rou_article_path(article),:method => :delete,:confirm =>'确定要删除么?',:class => 'btn btn-xs btn-danger' do  %>
                          <i class="icon-trash bigger-120"></i>
                        <% end %>

                      </div>

                    </td>
                  </tr>
                  <% end %>
                  </tbody>
                </table>
              </div>
              <!-- /.table-responsive -->
              <div class="digg_pagination">
                <%= will_paginate @articles,:previous_label => '<<上一页', :next_label => '下一页>>'  %>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>

    <div class="space-24"></div>

  </div>
  <!-- /.col -->
</div><!-- /.row -->

app/views/rou/articles/new.html.erb
<div class="main-content">
  <div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
      try {
        ace.settings.check('breadcrumbs', 'fixed')
      } catch (e) {
      }
    </script>

    <ul class="breadcrumb">
      <li>
        <i class="icon-home home-icon"></i>
        <a href="<%= rou_root_url %>">Home</a>
      </li>
      <li class="active">Article</li>
    </ul>
    <!-- .breadcrumb -->

    <!-- #nav-search -->
  </div>

  <div class="page-content">

    <div class="row">
      <div class="col-xs-12">
        <!-- PAGE CONTENT BEGINS -->

        <div class="row">
          <div class="col-sm-12 widget-container-span">
            <div class="widget-box">
              <div class="widget-header widget-hea1der-small header-color-dark">
                <h6><%= @web_title %></h6>
                <div class="widget-toolbar">
                  <%= link_to '新增', new_rou_article_path %>
                </div>
              </div>
              <%= render 'form' %>
            </div>

          </div>
        </div>
      </div>
    </div>

    <div class="space-24"></div>

  </div>
  <!-- /.col -->
</div><!-- /.row -->

app/views/rou/articles/show.html.erb
<div class="main-content">
  <div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
      try {
        ace.settings.check('breadcrumbs', 'fixed')
      } catch (e) {
      }
    </script>

    <ul class="breadcrumb">
      <li>
        <i class="icon-home home-icon"></i>
        <a href="<%= rou_root_url %>">Home</a>
      </li>
      <li class="active">Article</li>
    </ul>
    <!-- .breadcrumb -->

    <!-- #nav-search -->
  </div>

  <div class="page-content">

    <div class="row">
      <div class="col-xs-12">
        <!-- PAGE CONTENT BEGINS -->

        <div class="row">
          <div class="col-sm-12 widget-container-span">
            <div class="widget-box">
              <div class="widget-header widget-hea1der-small header-color-dark">
                <h6><%= @web_title %></h6>
                <div class="widget-toolbar">
                  <%= link_to '返回', rou_articles_path %>
                </div>
              </div>
              <h3 style="text-align: center"><%= @article.title %></h3>
              <%= raw @article.content %>
            </div>

          </div>
        </div>
      </div>
    </div>

    <div class="space-24"></div>

  </div>
  <!-- /.col -->
</div><!-- /.row -->